"""
Digest generation: render markdown and write provenance for selected articles.
"""
from __future__ import annotations

from datetime import datetime, date, timezone
from pathlib import Path
from typing import Any, Dict, List

from loguru import logger

from utils import save_provenance


class DigestGenerator:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.digest_dir = Path(config["output"]["digest_dir"])  # e.g., digests/
        self.provenance_dir = Path(config["output"]["provenance_dir"])  # e.g., provenance/
        self.date_format = config["output"]["date_format"]
        # Fixed topic display names and order
        self.topic_order = [
            ("LLMs", "LLMs — Top 5"),
            ("RAG", "RAG — Top 5"),
            ("MCP", "MCP (Model Context Protocol) — Top 5"),
            ("Quantum Computing", "Quantum computing — Top 5"),
        ]

    def generate(self, ranked: Dict[str, List[Dict[str, Any]]], target_date, output_dir: Path) -> Path:
        # Ensure directories exist
        self.digest_dir.mkdir(parents=True, exist_ok=True)
        self.provenance_dir.mkdir(parents=True, exist_ok=True)

        # Output file path
        date_str = target_date.strftime(self.date_format)
        md_path = self.digest_dir / f"{date_str}.md"

        # Header and intro
        fetch_time = datetime.utcnow().replace(tzinfo=timezone.utc).isoformat().replace("+00:00", "Z")
        header = [
            f"# Daily Tech Digest — {date_str}",
            "",
            "> Curated English-language articles about LLMs, RAG, MCP (Model Context Protocol), and Quantum computing.",
            "> Generated by: `digest-agent`  — fetch time: " + fetch_time,
            "",
            "---",
            "",
        ]

        # Sections per topic
        sections: List[str] = []
        provenance_records: List[Dict[str, Any]] = []
        for topic_key, heading in self.topic_order:
            articles = ranked.get(topic_key, [])
            sections.append(f"## {heading}")
            if not articles:
                sections.append("(No eligible articles found.)")
                sections.append("")
                sections.append("---")
                sections.append("")
                continue

            # Enforce exactly 5 items per topic (should already be trimmed)
            articles = articles[: self.config["output"]["max_articles_per_topic"]]

            lines: List[str] = []
            for idx, a in enumerate(articles, start=1):
                title = a.get("title", "Untitled").strip()
                url = a.get("url", "").strip()
                source = a.get("source") or ""
                authors = a.get("authors") or []
                authors_str = ", ".join(authors) if authors else "Unknown"
                pub = a.get("published")
                pub_str = pub.date().isoformat() if hasattr(pub, "date") else (str(pub) if pub else "")
                read_min = a.get("reading_time_min") or 0
                summary = a.get("summary", "").strip()
                why = a.get("why_selected", "").strip()

                lines.append(f"{idx}. **[{title}]({url})**  ")
                lines.append(f"   _Source_: {source} · _Author_: {authors_str} · _Published_: {pub_str} · _Reading time_: {read_min} min  ")
                lines.append(f"   **Summary:** {summary}  ")
                lines.append(f"   **Why selected:** {why}")
                lines.append("")

                # provenance record
                provenance_records.append({
                    "url": url,
                    "fetch_timestamp": (a.get("fetch_time") or datetime.utcnow()).isoformat(),
                    "http_status": a.get("http_status", 200),
                    "content_hash": a.get("content_hash", ""),
                    "topic": a.get("topic"),
                    "source": source,
                    "title": title,
                    # routing metadata if available
                    "routing": a.get("routing", {}),
                })

            sections.extend(lines)
            sections.append("---")
            sections.append("")

        # Notes & skipped items (basic placeholders for now)
        sections.append("## Notes & skipped items")
        sections.append("- Paywalled/blocked: none recorded in this run.")
        sections.append("- Crawled but low-quality or non-English examples: none recorded in this run.")
        sections.append("")

        # Provenance & logs
        sections.append("## Provenance & logs")
        sections.append(f"- `provenance/{date_str}.json`  contains fetch metadata, content-hashes, and scoring for reproducibility.")
        sections.append("")

        # Write markdown
        md_content = "\n".join(header + sections)
        md_path.write_text(md_content, encoding="utf-8")
        logger.success(f"Wrote digest markdown to {md_path}")

        # Write provenance JSON
        prov_path = save_provenance({"items": provenance_records}, self.config, target_date)
        logger.success(f"Wrote provenance to {prov_path}")

        return md_path
